<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

# What to expect in this chapter

# Lists, Arrays & Dictionaries

## Let’s compare

In [5]:
# Python Lists
py_songs = ["Eternal Flame", "True Blue", "Purple Rain"]
py_artists = ["The Bangles", "Madonna", "Prince"]

In [4]:
# Numpy Arrays
np_songs = np.array(["Eternal Flame", "True Blue", "Purple Rain"])
np_artists = np.array(["The Bangles", "Madonna","Prince"])

In [13]:
# Dictionary
songs_info = {
    "Eternal Flame": "The Bangles",
    "True Blue":  "Madonna",
    "Purple Rain": "Prince"
}

## Accessing data from a list (or array)

In [6]:
py_songs[0]

'Eternal Flame'

In [7]:
py_artists[0]

'The Bangles'

In [15]:
print(py_songs[0], 'is by', py_artists[0])

Eternal Flame is by The Bangles


In [16]:
i = 2
print(py_songs[i], 'is by', py_artists[i])

Purple Rain is by Prince


In [10]:
py_songs[2] # Forward indexing

'Purple Rain'

In [11]:
py_artists[-1] # Reverse indexing

'Prince'

## Accessing data from a dictionary

In [14]:
songs_info["Eternal Flame"]

'The Bangles'

In [17]:
songs_info.keys()

dict_keys(['Eternal Flame', 'True Blue', 'Purple Rain'])

In [18]:
songs_info.values()

dict_values(['The Bangles', 'Madonna', 'Prince'])

## Higher dimensional lists

In [21]:
py_songs_info = [["Eternal Flame", "The Bangles"],
    ["True Blue",  "Madonna"],
    ["Purple Rain", "Prince"]]

# Lists vs. Arrays

## Size

In [26]:
py_songs_info = [["Eternal Flame", "The Bangles"],
    ["True Blue",  "Madonna"],
    ["Purple Rain", "Prince"]]

np_songs_info = np.array(py_songs_info)

In [34]:
# List or Array
len(py_songs_info)

3

In [33]:
len(np_songs_info)

3

In [35]:
# Array only
np_songs_info.shape

(3, 2)

In [27]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [28]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [29]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

## Arrays are fussy about type

In [36]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [39]:
py_list

[1, 1.5, 'A']

In [38]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## Adding a number

In [44]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [42]:
# Array
np_array + 10

array([11, 12, 13, 14, 15])

In [43]:
# List
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

## Adding another list

In [45]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [47]:
# Array
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

In [49]:
# List
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

## Multiplying by a Number

In [50]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [53]:
# Array
np_array*2

array([ 2,  4,  6,  8, 10])

In [52]:
# List
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

## Squaring

In [54]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [57]:
# Array
np_array**2

array([ 1,  4,  9, 16, 25])

In [58]:
# List
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## Asking questions

In [59]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [65]:
# List
py_list == 3     # Works, but what IS the question?

False

In [64]:
py_list > 3

TypeError: '>' not supported between instances of 'list' and 'int'

In [66]:
# Array
np_array > 3 

array([False, False, False,  True,  True])

In [67]:
sum(np_array > 3 )

2

In [62]:
np_array == 3   

array([False, False,  True, False, False])

## Mathematics

In [68]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [69]:
sum(py_list)     # sum() is a base Python function

15

In [70]:
max(py_list)     # max() is a base Python function

5

In [71]:
min(py_list)     # min() is a base Python function

1

In [80]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [72]:
np_array.sum()

15

In [82]:
sum(np_array)

15

In [73]:
np_array.max()

5

In [75]:
np_array.min()

1

In [78]:
np_array.mean()

3.0

In [79]:
np_array.std()

1.4142135623730951

In [81]:
py_list = [1, 2, 3, 4, 5, 'A']
sum(py_list) 

TypeError: unsupported operand type(s) for +: 'int' and 'str'