<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [2]:
import numpy as np

# What to expect in this chapter

# Subsetting: Indexing and Slicing

## Lists & Arrays in 1D | Subsetting & Indexing

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = np_array

In [4]:
np_array

array(['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10'],
      dtype='<U3')

In [5]:
x[0]

'a1'

In [6]:
x[-1]	

'j10'

In [7]:
x[0:3]	

array(['a1', 'b2', 'c3'], dtype='<U3')

In [8]:
x[1:6]	

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [9]:
x[1:6:2]	

array(['b2', 'd4', 'f6'], dtype='<U3')

In [10]:
x[5:]	

array(['f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [11]:
x[:5]	

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [12]:
x[5:2:-1]

array(['f6', 'e5', 'd4'], dtype='<U3')

In [13]:
x[::-1]

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

In [14]:
x[::-2]

array(['j10', 'h8', 'f6', 'd4', 'b2'], dtype='<U3')

## Arrays only | Subsetting by masking

In [15]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [27]:
np_array > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [29]:
my_mask= np_array > 3

In [31]:
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [26]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [32]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [33]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [34]:
 np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [35]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## Lists & Arrays in 2D | Indexing & Slicing

In [36]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [43]:
 # What is at position 4 (index 3)?

In [53]:
# Array
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [52]:
# List
py_list_2d[3]

[4, 'D']

In [44]:
# What is the FIRST element at position 4 (index 3)

In [42]:
# Array
np_array_2d[3, 0]

'4'

In [48]:
# List
py_list_2d[3][0]

4

In [50]:
# What are the first three elements?

In [49]:
# Array
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [51]:
# List
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [60]:
# How to yield the first elements (i.e., [1, 2, 3]) of all the sub-lists up to index 2.

In [57]:
# Array
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [58]:
# List
py_list_2d[:3][0]

[1, 'A']

In [61]:
# It gives the first of the list you get from py_list_2d[:3]

In [65]:
# Array
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [67]:
# Array
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [66]:
# List
py_list_2d[3:6][0]

[4, 'D']

## Growing lists

In [68]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [69]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [70]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [71]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [72]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [73]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [74]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

In [77]:
x = [1, 2]
[4, 5, 6, 7] + x

[4, 5, 6, 7, 1, 2]

# Some loose ends


## Tuples

In [92]:
x = [1, 2, 3] # this is a list

In [93]:
x[0] = 56

In [94]:
x

[56, 2, 3]

In [79]:
a=(1, 2, 3)     # Define tuple

In [80]:
print(a[0])    # Access data

1


In [83]:
# The following will NOT work as tuples cannot be edited
a[0]=-1

TypeError: 'tuple' object does not support item assignment

In [84]:
a[0]+= [10]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

## Be VERY careful when copying

In [101]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [102]:
print(f'{id(x)=}', f'{id(y)=}', f'{id(z)=}')

id(x)=4895384384 id(y)=4895384384 id(z)=4895384384


In [103]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

In [104]:
print(f'{id(x)=}', f'{id(y)=}', f'{id(z)=}')

id(x)=4894917248 id(y)=4894556288 id(z)=4895188864
